### ISSUE TITLE
Fails to detect theater mode (sometimes) - container's ID may have changed again

### ISSUE THREAD

**Issue by Rhys-T** [maquinas07/yttwthmode#17]
Sometimes when I turn on theater mode, yttwthmode seems to not notice - I end up with the regular YouTube theater mode. Digging into the code, I found that the `#player-wide-container` element doesn't seem to exist. However, there is a `#player-full-bleed-container` that looks like it could be the replacement for it. In my limited testing[^testing], using `#player-full-bleed-container` as the `theaterContainer` seems to result in the correct layout as far as I can tell. (I see from #16 that this isn't the first time that element's ID has changed.)

[^testing]: I set a breakpoint at the equivalent of [`reloadPageElems`](https://github.com/maquinas07/yttwthmode/blob/e77942330463f42777d73b2fa7faeb239fe51e41/src/main.js#L31), reloaded the video page, then used the console to wrap the `getElementById` function: `const oldByID = document.getElementById; document.getElementById = function(id) { if(id === 'player-wide-container') id = 'player-full-bleed-container'; return oldByID.call(this, id); }`

However, in other sessions, yttwthmode seems to work just fine. That suggests that YouTube is still using the older ID sometimes, possibly as part of an A/B test. So it might be worth checking for both IDs with something like:
```js
theaterContainer = document.getElementById("player-full-bleed-container") || document.getElementById("player-wide-container");
```
or maybe even something like this, in case they change it yet again:
```js
// Get the first descendant of the pageManagerContainer whose ID looks like player-*-container
theaterContainer = pageManagerContainer.querySelector('[id^="player-"][id$="-container"]:not(#player-container)')
```

**Comment by maquinas07** [comment]
Thanks for the heads up! It has definitely happened before and I'm seeing the same behavior. Both of those changes look OK to me since the reloading only happens on initialization. I'll try to merge your querySelector patch with the hopes that they at least keep the naming convention.

**Comment by Rhys-T** [comment]
Seems to be working. Thanks!
