### ISSUE TITLE
Video extends behind chat, and has title, description etc. overlaid on top of it

### ISSUE THREAD

**Issue by Rhys-T** [maquinas07/yttwthmode#19]
Looks like YouTube has changed the page structure yet again. There's still a `#player-full-bleed-container` element, but it's been wrapped in another element `#full-bleed-container` that sits between it and the `ytd-watch-flexy.ytd-page-manager`. yttwthmode targets the inner one, and as a result, the player ends up partway under the chat, and the video information (title, description, and so on) appear overlaid on top of the video. Using the devtools to convince the extension to target `#full-bleed-container` instead seems to result in the correct layout again.

I'm not sure yet if this one is being A/B tested or not, but if you want to continue supporting the old structure as well, I can think of two ways to do this:

1. Update the `querySelector` call to look for two different selectors:
```js
theaterContainer = pageManagerContainer.querySelector(
	'#full-bleed-container, ' +
	'[id^="player-"][id$="-container"]:not(#player-container)'
);
```
`querySelector` will just return the first element it finds that matches either selector. That will be the outer `#full-bleed-container` if it's there, and the `#player-*-container` otherwise.

2. Use the existing selector, but then back out until you reach a direct child of `ytd-watch-flexy.ytd-page-manager`:
```js
theaterContainer = pageManagerContainer.querySelector('[id^="player-"][id$="-container"]:not(#player-container)');
theaterContainer = theaterContainer.closest('ytd-watch-flexy.ytd-page-manager > *');
```
That second line will do nothing if `theaterContainer` already is a direct child, like in the old structure.

I'm not sure which of those is more likely to keep working as YouTube continues changing things.

**Comment by maquinas07** [comment]
I'm also seeing the #full-bleed-container element, seems like they're in the middle of changing stuff. I'll try your second approach just in case they wrap things further but I'm also unsure as to what's best.

**Comment by maquinas07** [comment]
Merged and released, hopefully it works properly for more than one week this time. Thanks again!
