### ISSUE TITLE
Layout BUG

### ISSUE THREAD

**Issue by ramhaidar** [maquinas07/yttwthmode#21]
YouTube is currently conducting A/B testing with various layouts. This occurs occasionally when you are logged in, but always happens when you are not. One way to replicate this is by opening a YouTube livestream in incognito mode.

Here is a screenshot for reference:

![image](https://github.com/maquinas07/yttwthmode/assets/49301219/89e9a942-3736-4426-8216-c5a594155794)

**Comment by maquinas07** [comment]
I'm not being able to replicate it on Firefox or Chromium currently, I'll keep an eye on this.

**Comment by ramhaidar** [comment]
> I'm not being able to replicate it on Firefox or Chromium currently, I'll keep an eye on this.

maybe its only happening in chrome incognito 😢

**Comment by maquinas07** [comment]
I tried on Firefox private and normal windows and Chromium normal and incognito. Just to rule it out, do you have any other extensions interacting with YouTube?

**Comment by ramhaidar** [comment]
> I tried on Firefox private and normal windows and Chromium normal and incognito. Just to rule it out, do you have any other extensions interacting with YouTube?

Ah, I see. It might be another extension causing interference. I'll try disabling the other extensions to determine which one is causing this behavior

**Comment by ramhaidar** [comment]
I think you're correct. The issue was caused by another extension that was tampering with something inside the cookie. When I deleted this cookie and reloaded the Livestream, everything started working normally again.

![image](https://github.com/maquinas07/yttwthmode/assets/49301219/e85cb486-63f6-4e9c-a5f5-07adb55c1c91)
![image](https://github.com/maquinas07/yttwthmode/assets/49301219/6fd188d7-c613-4258-9cc2-22988a60f69d)
